version: '3.8'

services:
  editor:
    build:
      context: ./edit
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/app/shared
    environment:
      - EDITOR_PORT=80
      - PREVIEW_PORT=3010
    depends_on:
      - preview
    networks:
      - reactstream-network

  preview:
    build:
      context: ./preview
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./public:/app/shared
    environment:
      - PREVIEW_PORT=3010
    networks:
      - reactstream-network

networks:
  reactstream-network:
    driver: bridge
