version: '3.8'

services:
  editor:
    build:
      context: ./editor
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - EDITOR_PORT=80
      - PREVIEW_URL=http://preview:3010
      - CODEBASE_URL=http://codebase:3020
    depends_on:
      - preview
      - codebase
    networks:
      - reactstream-network
    volumes:
      - editor_node_modules:/app/node_modules

  preview:
    build:
      context: ./preview
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - PREVIEW_PORT=3010
      - CODEBASE_URL=http://codebase:3020
    volumes:
      - preview_templates:/app/templates
      - preview_node_modules:/app/node_modules
    networks:
      - reactstream-network

  codebase:
    build:
      context: ./codebase
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    environment:
      - PORT=3020
      - NODE_ENV=production
      - SESSION_SECRET=your_session_secret_here
    volumes:
      - codebase_repositories:/app/repositories
      - codebase_node_modules:/app/node_modules
    networks:
      - reactstream-network

networks:
  reactstream-network:
    driver: bridge

volumes:
  editor_node_modules:
  preview_node_modules:
  preview_templates:
  codebase_node_modules:
  codebase_repositories:
